// Generated by https://quicktype.io
//
// To change quicktype's target language, run command:
//
//   "Set quicktype target language"

export interface IUser {
    email?:           string;
    emailVerified?:   boolean;
    isAnonymous?:     boolean;
    uid?:             string;
    phoneNumber?: string;
    photoURL?:    string;
    firstName?:   string;
    lastName?:    string;
    address?:      string;
    dob?: string;
}
export interface IInitUser {
    email:           string;
    phoneNumber: number;
    image?:    File[];
    firstName:   string;
    lastName:    string;
    address?:     string;
    password:string;
    dob?: string;
}

//create an interface for address
export interface IAddress {
    address1: string;
    address2?: string;
    city: string;
    state: string;
    zip?: string;
    postalCode?: string;
    country: string;
}

export interface PropertyIdAndImages  { 
    propertyId: string;
    images: File[];
}

